# Generated by Django 5.1.2 on 2024-10-14 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazenamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacoArmazenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveBigIntegerField(unique=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='armazenamento.produto')),
            ],
        ),
    ]
