# Generated by Django 5.1.2 on 2024-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazenamento', '0002_espacoarmazenamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='NF',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='sku',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(default='NF', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
