# Generated by Django 5.1.2 on 2024-10-15 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazenamento', '0004_alter_produto_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazenamento.espacoarmazenamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armazenamento.produto')),
            ],
        ),
    ]
