# Generated by Django 5.1.2 on 2024-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazenamento', '0005_registroentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrega',
            name='numero',
            field=models.PositiveBigIntegerField(default='1', unique=True),
            preserve_default=False,
        ),
    ]
