# Generated by Django 5.1.2 on 2024-10-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armazenamento', '0006_registroentrega_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroentrega',
            name='numero',
        ),
    ]
