# Generated by Django 5.1.2 on 2024-10-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armazenamento', '0007_remove_registroentrega_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacoarmazenamento',
            name='vaga',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cidade',
            field=models.CharField(max_length=50),
        ),
    ]
