# Generated by Django 5.1.2 on 2024-11-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armazenamento", "0009_alter_espacoarmazenamento_vaga"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="destino",
            field=models.CharField(blank=True, max_length=1362, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="origem",
            field=models.CharField(blank=True, max_length=1362, null=True),
        ),
    ]
