# Generated by Django 5.1.2 on 2024-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armazenamento", "0010_produto_destino_produto_origem"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aguardando", "aguardando Transpor"),
                    ("em_transito", "Em Transito"),
                    ("entregue", "Entregue"),
                ],
                default="aguardando",
                max_length=25,
                null=True,
            ),
        ),
    ]
