# Generated by Django 5.1.2 on 2024-11-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("armazenamento", "0010_produto_destino_produto_origem"),
    ]

    operations = [
        migrations.CreateModel(
            name="rota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origem", models.CharField(max_length=255)),
                ("destino", models.CharField(max_length=255)),
                ("distancia", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tempo_estimado", models.DurationField()),
                (
                    "custo_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="armazenamento.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Viagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_partida", models.DateTimeField()),
                ("data_chegada", models.DateTimeField(blank=True, null=True)),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="armazenamento.produto",
                    ),
                ),
                (
                    "rota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="rotas.rota"
                    ),
                ),
            ],
        ),
    ]
