# Generated by Django 5.1.2 on 2024-11-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rotas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rota",
            name="distancia",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rota",
            name="tempo_estimado",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
